name: SecurePipe Security Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov-scan:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: phase3-scanner
          framework: terraform
          output_format: cli
          soft_fail: true

  tfsec-scan:
    name: tfsec IaC Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: phase3-scanner
          soft_fail: true

  gitleaks-scan:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}